name = "shorturl"
type = "javascript"
account_id = "e9fd14e89272dcebc137bd7c422aaf05"
workers_dev = true
route = ""
zone_id = "e9fd14e89272dcebc137bd7c422aaf05"

kv_namespaces = [
    { binding = "SHORTURLS", preview_id = "5655fdafebc74b30ae7478712aae7b8b", id = "14ec4e4e5ee04275ac223ff8b7ed7756" }
]