name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest    
    
    steps:      
      - name: Checkout GitHub repo      
        uses: actions/checkout@v2

      - name: Publish createshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/readshorturl'
      
      - name: Publish createshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/createshorturl'

      - name: Publish updateshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/updateshorturl'

      - name: Publish deleteshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/deleteshorturl'

      - name: Publish redirectshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/redirectshorturl'
