name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest    
    
    steps:      
      - name: Checkout GitHub repo      
        uses: actions/checkout@v2

      - name: Publish shorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'shorturl'
      
      - name: Publish createshorturl Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'createshorturl'